version: 2
updates:
  - package-ecosystem: "npm" # npm manages jQuery if installed via package.json
    directory: "/js" # Adjust based on where package.json is located
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "jquery" # Optional: Ignore specific versions if needed
        versions: ["3.x"]
    labels:
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
